# Don't automatically run this pipeline
trigger: none
pr: none

variables:
  BuildConfiguration: Release

jobs:
- job: Build
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      x86:
        BuildPlatform: x86
      x64:
        BuildPlatform: x64
      ARM:
        BuildPlatform: ARM
      ARM64:
        BuildPlatform: ARM64
  steps:
  - template: build.yml
    parameters:
      ArtifactName: PlaneFinding
      SolutionPath: $(Build.SourcesDirectory)/SpatialMapping/PlaneFinding/PlaneFinding.sln
      BuildOutputPath: $(Build.SourcesDirectory)/SpatialMapping/PlaneFinding/Release

- job: Sign
  dependsOn: Build
  pool:
    name: Package ES Lab E
  steps:
  - template: sign.yml
    parameters:
      ArtifactName: PlaneFinding
      UnityFolderPath: $(Build.SourcesDirectory)/SpatialMapping/PlaneFinding/UnityAddon

- job: Pack
  dependsOn: Sign
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: pack.yml
    parameters:
      ArtifactName: UPMFolder_PlaneFinding