parameters:
- name: ProjectFriendlyName
  type: string
  default: ''
- name: SolutionPath
  type: string
  default: ''
- name: BuildOutputPath
  type: string
  default: ''
- name: UnityFolderPath
  type: string
  default: ''
- name: BuildVmImage
  type: string
  default: 'windows-2019'
- name: Sign
  type: boolean
  default: false
- name: SignConfigPath
  type: string
  default: ''

variables:
  BuildConfiguration: Release

jobs:
- job: Build_${{ parameters.ProjectFriendlyName }}
  pool:
    vmImage: ${{ parameters.BuildVmImage }}
  strategy:
    matrix:
      x86:
        BuildPlatform: x86
      x64:
        BuildPlatform: x64
      ARM:
        BuildPlatform: ARM
      ARM64:
        BuildPlatform: ARM64
  steps:
  - template: build.yml
    parameters:
      ArtifactName: ${{ parameters.ProjectFriendlyName }}
      SolutionPath: ${{ parameters.SolutionPath }}
      BuildOutputPath: ${{ parameters.BuildOutputPath }}

- job: Sign_${{ parameters.Sign }}
  dependsOn: Build_${{ parameters.ProjectFriendlyName }}
  pool:
    name: Package ES Lab E
  steps:
  - template: sign.yml
    parameters:
      ArtifactName: ${{ parameters.ProjectFriendlyName }}
      UnityFolderPath: ${{ parameters.UnityFolderPath }}
      Sign: ${{ parameters.Sign }}
      SignConfigPath: ${{ parameters.SignConfigPath }}

- job: Pack
  dependsOn: Sign_${{ parameters.Sign }}
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: pack.yml
    parameters:
      ArtifactName: UPMFolder_${{ parameters.ProjectFriendlyName }}
